// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: webcast.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;

namespace TikTok
{

    /// <summary>
    /// WebcastResponse là lớp chính chứa một danh sách các message.
    /// Mỗi message trong danh sách có thể là một loại sự kiện khác nhau (bình luận, like,...)
    /// </summary>
    public sealed partial class WebcastResponse : pb::IMessage<WebcastResponse>
    {
        private static readonly pb::MessageParser<WebcastResponse> _parser = new pb::MessageParser<WebcastResponse>(() => new WebcastResponse());
        private pb::UnknownFieldSet _unknownFields;

        // MessageParser là công cụ dùng để giải mã dữ liệu Protobuf thành đối tượng WebcastResponse.
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<WebcastResponse> Parser { get { return _parser; } }

        // Descriptor chứa thông tin mô tả về lớp này, lấy từ định nghĩa trong file .proto.
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::TikTok.WebcastReflection.Descriptor.MessageTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public WebcastResponse()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public WebcastResponse(WebcastResponse other) : this()
        {
            // Clone danh sách messages từ đối tượng khác
            messages_ = other.messages_.Clone();
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public WebcastResponse Clone()
        {
            return new WebcastResponse(this);
        }

        /// <summary>Field number for the "messages" field.</summary>
        public const int MessagesFieldNumber = 1;

        // RepeatedField là một collection đặc biệt của Protobuf để xử lý danh sách.
        private static readonly pb::FieldCodec<global::TikTok.Message> _repeated_messages_codec
            = pb::FieldCodec.ForMessage(10, global::TikTok.Message.Parser);
        private readonly pbc::RepeatedField<global::TikTok.Message> messages_ = new pbc::RepeatedField<global::TikTok.Message>();

        /// <summary>
        /// Đây là thuộc tính chứa danh sách các message của Webcast.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public pbc::RepeatedField<global::TikTok.Message> Messages
        {
            get { return messages_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other)
        {
            return Equals(other as WebcastResponse);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(WebcastResponse other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            // So sánh nội dung của danh sách messages.
            if (!messages_.Equals(other.messages_)) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode()
        {
            int hash = 1;
            hash ^= messages_.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output)
        {
            messages_.WriteTo(output, _repeated_messages_codec);
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(output);
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize()
        {
            int size = 0;
            size += messages_.CalculateSize(_repeated_messages_codec);
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(WebcastResponse other)
        {
            if (other == null)
            {
                return;
            }
            messages_.Add(other.messages_);
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                        break;
                    case 10:
                        {
                            messages_.AddEntriesFrom(input, _repeated_messages_codec);
                            break;
                        }
                }
            }
        }
    }

    #endregion
}